      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Certificate
      metadata:
        name: webhook-testing
        namespace: kaka
      spec:
        secretName: webhook-testing-cert
        commonName: "webhook-testing-root-ca"
        dnsNames:
        - webhooks.kaka.svc
        isCA: true
        issuerRef:
          name: selfsigning-issuer
          kind: ClusterIssuer

