kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-operator
subjects:
- kind: ServiceAccount
  name: nginx-operator
  namespace: test1
roleRef:
  kind: ClusterRole
  name: nginx-operator
  apiGroup: rbac.authorization.k8s.io
