---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: validating-operator
  template:
    metadata:
      labels:
        name: validating-operator
    spec:
      serviceAccountName: validating-operator
      containers:
        - name: validating-operator
          # Replace this with the built image name
          image: "quay.io/jfan/validat-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "validating-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
        - name: webhooks
          image: "quay.io/jfan/webhook-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /app/tls/
            name: webhook-testing-cert
      volumes:
        - name: runner
          emptyDir: {}
        - name: webhook-testing-cert
          secret:
            secretName: webhook-testing-cert
