    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: validating-test.fabianism.us
      annotations:
        certmanager.k8s.io/inject-ca-from: 'kaka/webhook-testing'
    webhooks:
    - name: validating-test.fabianism.us
      rules:
      - apiGroups:   ["test.fabianism.us"]
        apiVersions: ["*"]
        operations:  ["CREATE"]
        resources:   ["validatingtests"]
        scope:       "Namespaced"
      clientConfig:
        service:
          namespace: kaka
          name: webhooks
          path: /validating
      failurePolicy: Fail
      sideEffects: None
      admissionReviewVersions: ["v1"]
