    apiVersion: v1
    kind: Service
    metadata:
      name: webhooks
      namespace: kaka
    spec:
      ports:
      - name: webhook
        port: 443
        protocol: TCP
        targetPort: 5000
      selector:
        name: validating-operator
      type: ClusterIP
